# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

steps:


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/node:lts
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  push-gh-pages:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Generate index.html on gh-pages branch"
          command: |
            npx @redocly/cli build-docs definitions/spec.yaml --title="Experimental API Docs" --output=index.html
            git stash
            git checkout gh-pages
            rm index.html
            git stash pop
      - run:
          name: "Push new index.html to gh-pages branch"
          command: |
            git add index.html
            git commit -m "Regenerate index.html"
            git push origin gh-pages


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - push-gh-pages:
          filters:
            branches:
              only: main
