# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

general:
  branches:
    ignore:
      - gh-pages

orbs:
  gh-pages: sugarshin/gh-pages@1.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  render-docs:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Generate index.html"
          command: |
            mkdir dist
            npx @redocly/cli build-docs definitions/spec.yaml --title="Experimental API Docs" --output=./dist/index.html
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - render-docs
      - gh-pages/deploy:
          filters:
            branches:
              only: main
          requires:
            - render-docs
          ssh-fingerprints: 3d:53:cf:a9:6c:03:42:f9:b6:96:0a:5a:fc:00:54:98
